version: "3.1"

services:
  app-payment:
    container_name: service-payment-app
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: satellite-images
    networks:
      - service-payment
    volumes:
      - ../:/usr/share/app
      - ./config/php.ini/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    environment:
      - ENVIRONMENT=development

  nginx-payment:
    container_name: service-payment-nginx
    image: nginx
    env_file:
      - ../.env
    restart: always
    networks:
      - service-payment
    links:
      - app-payment
    depends_on:
      - app-payment
    ports:
      - "8083:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/servers:/etc/nginx/servers
      - ./keys/nginx:/keys
      - ../:/usr/share/app

networks:
  service-payment: {}
